import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { cn } from "@/lib/utils";
import type { Signal } from "@/lib/algorithm-types";
import { formatRelative } from "@/lib/format";

interface Props {
  signals: Signal[];
}

const signalStyles: Record<Signal["signal"], string> = {
  BUY: "bg-success/10 text-success border-success/20",
  SELL: "bg-destructive/10 text-destructive border-destructive/20",
  HOLD: "bg-warning/10 text-warning border-warning/20",
};

export function SignalsTable({ signals }: Props) {
  return (
    <Card className="gradient-card border-border shadow-card overflow-hidden">
      <div className="px-5 py-4 border-b border-border">
        <h3 className="font-semibold tracking-tight">Live Signals</h3>
        <p className="text-xs text-muted-foreground mt-0.5">
          Latest signals generated by this algorithm
        </p>
      </div>
      {signals.length === 0 ? (
        <div className="p-10 text-center text-sm text-muted-foreground">No signals available</div>
      ) : (
        <Table>
          <TableHeader>
            <TableRow className="hover:bg-transparent">
              <TableHead>Pair</TableHead>
              <TableHead>Signal</TableHead>
              <TableHead className="text-right">Price</TableHead>
              <TableHead className="text-right">Confidence</TableHead>
              <TableHead className="text-right">Time</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {signals.map((s) => (
              <TableRow key={s.id}>
                <TableCell className="font-medium">{s.pair}</TableCell>
                <TableCell>
                  <Badge variant="outline" className={cn("font-semibold", signalStyles[s.signal])}>
                    {s.signal}
                  </Badge>
                </TableCell>
                <TableCell className="text-right tabular">
                  ${s.price.toLocaleString(undefined, { maximumFractionDigits: 4 })}
                </TableCell>
                <TableCell className="text-right tabular">{s.confidence.toFixed(0)}%</TableCell>
                <TableCell className="text-right text-muted-foreground text-xs">
                  {formatRelative(s.time)}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      )}
    </Card>
  );
}
