/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortfoliosRouteImport } from './routes/portfolios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlgorithmsIndexRouteImport } from './routes/algorithms.index'
import { Route as AlgorithmsAlgoIdRouteImport } from './routes/algorithms.$algoId'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoliosRoute = PortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsIndexRoute = AlgorithmsIndexRouteImport.update({
  id: '/algorithms/',
  path: '/algorithms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsAlgoIdRoute = AlgorithmsAlgoIdRouteImport.update({
  id: '/algorithms/$algoId',
  path: '/algorithms/$algoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/crypto': typeof CryptoRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/portfolios': typeof PortfoliosRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stocks': typeof StocksRoute
  '/watchlist': typeof WatchlistRoute
  '/algorithms/$algoId': typeof AlgorithmsAlgoIdRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/crypto': typeof CryptoRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/portfolios': typeof PortfoliosRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stocks': typeof StocksRoute
  '/watchlist': typeof WatchlistRoute
  '/algorithms/$algoId': typeof AlgorithmsAlgoIdRoute
  '/algorithms': typeof AlgorithmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/crypto': typeof CryptoRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/portfolios': typeof PortfoliosRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stocks': typeof StocksRoute
  '/watchlist': typeof WatchlistRoute
  '/algorithms/$algoId': typeof AlgorithmsAlgoIdRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/crypto'
    | '/dashboard'
    | '/login'
    | '/portfolios'
    | '/profile'
    | '/settings'
    | '/stocks'
    | '/watchlist'
    | '/algorithms/$algoId'
    | '/algorithms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/crypto'
    | '/dashboard'
    | '/login'
    | '/portfolios'
    | '/profile'
    | '/settings'
    | '/stocks'
    | '/watchlist'
    | '/algorithms/$algoId'
    | '/algorithms'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/crypto'
    | '/dashboard'
    | '/login'
    | '/portfolios'
    | '/profile'
    | '/settings'
    | '/stocks'
    | '/watchlist'
    | '/algorithms/$algoId'
    | '/algorithms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CryptoRoute: typeof CryptoRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PortfoliosRoute: typeof PortfoliosRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  StocksRoute: typeof StocksRoute
  WatchlistRoute: typeof WatchlistRoute
  AlgorithmsAlgoIdRoute: typeof AlgorithmsAlgoIdRoute
  AlgorithmsIndexRoute: typeof AlgorithmsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolios': {
      id: '/portfolios'
      path: '/portfolios'
      fullPath: '/portfolios'
      preLoaderRoute: typeof PortfoliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/': {
      id: '/algorithms/'
      path: '/algorithms'
      fullPath: '/algorithms/'
      preLoaderRoute: typeof AlgorithmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/$algoId': {
      id: '/algorithms/$algoId'
      path: '/algorithms/$algoId'
      fullPath: '/algorithms/$algoId'
      preLoaderRoute: typeof AlgorithmsAlgoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CryptoRoute: CryptoRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PortfoliosRoute: PortfoliosRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  StocksRoute: StocksRoute,
  WatchlistRoute: WatchlistRoute,
  AlgorithmsAlgoIdRoute: AlgorithmsAlgoIdRoute,
  AlgorithmsIndexRoute: AlgorithmsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
